version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"  # Expose MongoDB on default port
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=mydatabase
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

volumes:
  mongo_data:
    driver: local
